### PR TITLE
Fixes core#19 - GET JSON Schema for Metadata

### PR DESCRIPTION
**Pull request by luan-cestari**
This PR aims to create the service to generate the json schema of an entity as described in https://github.com/lightblue-platform/lightblue-core/issues/19 . 

Depends on https://github.com/lightblue-platform/lightblue-core/pull/276  (merge it before this PR)

There was some issues with RDBMS test as the RDBMS module needs to be updated with the latest changes of the core module and the rdbms will not be changed right now, so I used @Ignore on that test.

### CODE REVIEW

**Comment by luan-cestari** [comment]
The build failed as the rest module is outdated witht he core changes. The PR https://github.com/lightblue-platform/lightblue-rest/pull/98 fix this problem

**Comment by jewzaam** [comment]
#98 is merged, please merge to this PR.

**Comment by luan-cestari** [comment]
Merged

**Comment by jewzaam** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project lightblue-rest-crud: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/lightblue-platform/lightblue-rest/crud/src/test/java/com/redhat/lightblue/rest/crud/ITCaseCrudResourceTest.java:[206,23] error: cannot find symbol
[ERROR] class FileUtil
[ERROR] /home/travis/build/lightblue-platform/lightblue-rest/crud/src/test/java/com/redhat/lightblue/rest/crud/ITCaseCrudResourceRDBMSTest.java:[265,23] error: cannot find symbol
```

**Comment by luan-cestari** [comment]
It didn't compile due the PR https://github.com/lightblue-platform/lightblue-core/pull/276 wasn't merged yet

**Comment by luan-cestari** [comment]
pending the PR https://github.com/lightblue-platform/lightblue-core/pull/276 be merged (related to the issue https://github.com/lightblue-platform/lightblue-core/issues/19 )

**Pull request closed without merging**
