### PR TITLE
Fixes #300: Default query to objectType:entityName in simple find

### PR DESCRIPTION
**Pull request by alechenninger**
Closes https://github.com/lightblue-platform/lightblue-core/issues/300

### CODE REVIEW

**Comment by alechenninger** [comment]
I'd write a unit test for this but it is hard to test lightblue-rest because of lack of dependency injection.

**Comment by alechenninger** [comment]
Actually, I think I could use `RestConfiguration.setFactory`...

**Comment by bserdar** [comment]
This is not the best way to do this. Lets make query optional for find()
operation in core, and then you can pass empty query.

**Comment by alechenninger** [comment]
It seemed like since there were already defaults in the simple find query, it fit neatly here. You cannot pass an empty projection, for instance, but you can in the simple find query.

**Comment by jewzaam** [comment]
Query is now optional: https://github.com/lightblue-platform/lightblue-core/pull/432

**Pull request closed without merging**
