### PR TITLE
Rdbms tests refactor

### PR DESCRIPTION
**Pull request by jewzaam**
Updates to crud tests in general after review of rdbms_tests to bring a bit more clarity/sanity to the test resources used by each integration.

Also cleaned up other tests in this process, pulling some common arquillian setup to an abstract class.  More could be done but decided not to.

Depends on https://github.com/lightblue-platform/lightblue-rest/pull/55

### CODE REVIEW

**Comment by luan-cestari** [comment]
It can't be merged. Moving this PR to in progress

**Comment by jewzaam** [comment]
Updated and moved back to in progress.

**Comment by jewzaam** [comment]
I mean back to ready for review..

**Comment by jewzaam** [comment]
Updated with latest master...

**Pull request merged**
