### PR TITLE
fixes #142 - more defensive code and handle actual audit in async thread

### LINKED ISSUE #142: Hystrix timeouts
We started to get the below exception on Friday April 24th at around 9AM. The only snapshot build for that day was based off git hash 32d58f16965854d0455ccaecd35f84750a336fea. Which was for https://github.com/lightblue-platform/lightblue-rest/pull/128. We need to investigate to see what is going on.

```
015-04-29 09:52:45,244 [https_executor-threads - 383] ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/rest/data].[com.redhat.lightblue.rest.crud.RestApplication]] JBWEB000236: Servlet.service() for servlet com.redhat.lightblue.rest.crud.RestApplication threw exception: org.jboss.resteasy.spi.UnhandledException: com.netflix.hystrix.exception.HystrixRuntimeException: FindCommand timed-out and no fallback available.
	at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:365)
	at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:233)
	at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:557)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at com.redhat.lightblue.rest.audit.LightblueAuditServletFilter.doFilter(LightblueAuditServletFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:438)
	at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:508)
	at org.jboss.threads.SimpleDirectExecutor.execute(SimpleDirectExecutor.java:33)
	at org.jboss.threads.QueueExecutor.runTask(QueueExecutor.java:806)
	at org.jboss.threads.QueueExecutor.access$100(QueueExecutor.java:45)
	at org.jboss.threads.QueueExecutor$Worker.run(QueueExecutor.java:847)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: FindCommand timed-out and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:760)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:747)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1388)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1278)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.run(AbstractCommand.java:867)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:37)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:57)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$2.tick(AbstractCommand.java:887)
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException
	at com.netflix.hystrix.AbstractCommand$8.call(AbstractCommand.java:581)
	at com.netflix.hystrix.AbstractCommand$8.call(AbstractCommand.java:562)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	... 15 more
```

### PR DESCRIPTION
**Pull request by dcrissman**
Fixes an issue where audits were taking too long causing hystrix connections to time out. This fix will handle the actual auditing heavy lifting in a separate async thread.

### CODE REVIEW

**Comment by luan-cestari** [comment]
I don't recommend creating an thread and running it manually without a pool.
Also, SimpleDateFormat doesnt support concurrency (I noticed you removed the threadlocal). You may want to use the fast simple date format from apache commons which supports (I think it wasnt present on the previous version of the library that we used to use)

I would also move this line https://github.com/lightblue-platform/lightblue-rest/pull/143/files#diff-ce797dd71bde9a4653f869b157e704f2R54 a bit above, before it log that is is auditing 

Also, I think the log implementation might have an async feature which would be nice to investigate (which would not need all these changes)

**Comment by dcrissman** [comment]
Requested changes have been made.

**Comment by dcrissman** [comment]
Failures were due to a broken unit test in master, that has now been fixed.

**Comment by luan-cestari** [comment]
@dcrissman I would suggest to move the AuditLogWritter class out and maybe delay the simplatedateformat initialization ('''new SimpleDateFormat(YYYY_MM_DD_T_HH_MM_SS_SSSZ).format(new Date())''') (not a big issue but it might save some time as well)

**Comment by dcrissman** [comment]
Changes made as requested

**Comment by luan-cestari** [comment]
@dcrissman  Also, about the thread pool, I would expect it so set the core and max size (not be able to exhaust the cpu or run out the memory ). It would be also needed to set a bounded queue (we don't want it to use all the memory as well) as a ThreadFactory (so we can see clearly the thread that lightblue create during a profiling or  debuging)

**Comment by bserdar** [comment]
If the purpose of the audit is to keep track of changes so when someone
asks, we can track the history, then the assumption that "if audit fails,
crud operation should still continue" is wrong. In that case, writing
audits in a separate thread is asking for trouble.

In my experience, the only time when someone asks about an audit is when
legal is tracking some change. And they don't like to hear that we don't
audit everything,

**Comment by dcrissman** [comment]
@bserdar The audit would happen after the crud operation was successful anyway. So we would get an exception, but the action would still have occurred. No sense in returning an error to the user for an internal matter.

**Comment by dcrissman** [comment]
Requested changes made.

**Comment by bserdar** [comment]
If audit fails, crud operation should fail as well.

**Comment by dcrissman** [comment]
@jewzaam what was the original intent of #120? Was it for legal purposes?

@bserdar prior to my changes LightblueAuditServletFilter already wrapped the crud action in a way that the action would still have been completed. I am not sure how we could roll back an operation if audit logging failed.

**Comment by bserdar** [comment]
This is one of the reasons why I wanted to introduce transactions. An
unreliable audit record is worse than not having an audit record.

For now, it is acceptable to fail the call if audit fails. Eventually when
we introduce transactions, we can roll back.

In any case, it is still a bad idea to audit in a separate thread.

**Comment by dcrissman** [comment]
After some further discussions, I will close this PR pending some additional analysis.

**Pull request closed without merging**
