### PR TITLE
bump to next major version

### PR DESCRIPTION
**Pull request by dcrissman**
related to https://github.com/lightblue-platform/lightblue-rest/issues/162

The issue changes how plugins are loaded into lightblue, because of that I feel a bump in major version is warranted.

### CODE REVIEW

**Comment by dcrissman** [comment]
There is some discussion around the definition of a "breaking change".

**Comment by bserdar** [comment]
My understanding is that a breaking change implies major version update,
but not the other way around. Major version updates don't have to be
breaking changes.

**Comment by dcrissman** [comment]
The change in #162 alters how "plugins" are loaded. While not technically a code breaking change, no longer will "plugins" just be made available in lightblue-rest as a maven dependency. Instead each will need to be individually installed and configured on the host.

If an existing deployment of lightblue were to be upgraded, functionality could be potentially lost. Because of this, I think a major version change would help indicate to the deployment owner that they need to be aware that something big changed. I also created https://github.com/lightblue-platform/lightblue-docs-specs/issues/34 to write documentation for this.

**Comment by dcrissman** [comment]
A point @jewzaam made.

> This isn't breaking to existing deployments unless they had those hooks configured.

This is true. A ClassNotFoundException would be thrown on the server the first time a data or metadata request was processed as that is when the LightblueFactory is lazy loaded.

**Pull request merged**
